language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"
env:
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.2.2
#    - MAGENTO_VERSION=magento-ce-1.7.0.2
#    - MAGENTO_VERSION=magento-ce-1.6.2.0
install:
  - git submodule init
  - git submodule update

script:
  - sh travis.ci.sh
